language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.pip --use-mirrors
  - sudo python manage.py related_fields_patch
# command to run tests
script: python manage.py test
